name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=master-devops-cloud2_HAFIANI_Salma_Gates \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=master-devops-cloud2 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload Quality Gate Status (Optional)  
        run: echo "SonarQube Quality Gate Check Complete"
